### ISSUE TITLE
Access denied while pushing a branch

### ISSUE THREAD

**Issue by prabhakarniraula** [DDUCE/Automazo-android-automation#1]
@purvisoni After selecting "Commit & Push" option from android studio it provides following error : 

Push failed
Failed with error: fatal: unable to access 'https://github.com/DDUCE/Automazo-android-automation.git/': The requested URL returned error: 403 

Which is generated because access of repository for team members is not granted.

**Comment by purvisoni** [comment]
@prabhakarniraula, "Write" Privilege is assigned. Now all should able to push. let me know your response.
